server.port: ${PORT:9090}

spring:
  cloud:
    stream:
      defaultBinder: servicebus-1

      function:
        definition:
          consumidorFila;
          investimentoResgateProducer;
        bindings:
          consumidorFila-in-0: rendafixa-input
          investimentoResgateProducer-out-0: rendafixa-output

      bindings:
        rendafixa-input:
          binder: servicebus-1
          destination: next-lab-rendafixa-queue
          contentType: application/json

        rendafixa-output:
          binder: servicebus-1
          destination: next-lab-rendafixa-queue
          contentType: application/json

      binders:
        servicebus-1:
          type: servicebus
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    connection-string: Endpoint=sb://next-stream-ra.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=kfDKtdkf9BCCnWbC2aNGuFxXSOWlw+xbmnZg9QTSzUc=

      servicebus:
        bindings:
          rendafixa-input:
            consumer:
              auto-complete: true
          rendafixa-output:
            producer:
              entity-type: queue
            sync: true

      poller:
        fixed-delay: 1000
        initial-delay: 0