server.port: ${PORT:9090}

spring:
  cloud:
    stream:
      function:
        definition: consumidorFila;produtorFila;
      bindings:
        consumidorFila-in-0:
          binder: servicebus-1
          destination: next-lab-rendafixa-queue
        produtorFila-out-0:
          binder: servicebus-1
          destination: next-lab-rendafixa-queue
      binders:
        servicebus-1:
          type: servicebus
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    connection-string: Endpoint=sb://next-stream-ra.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=kfDKtdkf9BCCnWbC2aNGuFxXSOWlw+xbmnZg9QTSzUc=
      servicebus:
        bindings:
          consumidorFila-in-0:
            consumer:
              auto-complete: false
          produtorFila-out-0:
            producer:
              entity-type: queue
      poller:
        fixed-delay: 1000
        initial-delay: 0