server.port: ${PORT:9090}

spring:
  cloud:
    stream:
      defaultBinder: servicebus-1

      function:
        definition:
          investimentoResgateConsumer;
          investimentoResgateProducer;
          movimentacaoFinanceiraConsumer;
          movimentacaoFinanceiraProducer;
        bindings:
          investimentoResgateConsumer-in-0: rendafixa-input
          investimentoResgateProducer-out-0: rendafixa-output
          movimentacaoFinanceiraConsumer-in-0: movimentacao-input
          movimentacaoFinanceiraProducer-out-0: movimentacao-output

      bindings:
        # FILA
        rendafixa-input:
          destination: next-lab-rendafixa-queue
          contentType: application/json
        rendafixa-output:
          destination: next-lab-rendafixa-queue
          contentType: application/json

        # TOPICO
        movimentacao-output:
          destination: next-lab-rendafixa-topic
          contentType: application/json
        movimentacao-input:
          destination: next-lab-rendafixa-topic
          contentType: application/json
          group: rendafixa-resgate-core

      binders:
        servicebus-1:
          type: servicebus
          default-candidate: true
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    connection-string: Endpoint=sb://next-stream-ra.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=kfDKtdkf9BCCnWbC2aNGuFxXSOWlw+xbmnZg9QTSzUc=

      servicebus:
        bindings:
          # FILA
          rendafixa-input:
            consumer:
              auto-complete: true
          rendafixa-output:
            producer:
              entity-type: queue
            sync: true
          # TOPICO
          movimentacao-input:
            consumer:
              auto-complete: false
          movimentacao-output:
            producer:
              entity-type: topic

      poller:
        fixed-delay: 1000
        initial-delay: 0